### ISSUE TITLE
Full release TODO

### ISSUE THREAD

**Issue by DoumanAsh** [DoumanAsh/xxhash-rust#2]
MUST HAVE:

- [x] AVX acceleration
    - [x] AVX2
    - [ ] ~AVX512~ - Not stable :(

GOOD TO HAVE:

- [ ] Full match in performance with C reference implementation ~(xxh3 has small deviation on small inputs)~
- [ ] Neon SIMD, but as Rust hasn't made it stable we probably can postpone it
